**Домашнее задание**

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [49]:
import numpy as np

In [50]:
N = 10
a = np.arange(N-1, -1, -1)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [56]:
def matrix_sum():
    user_input = int(input('Введите число N: '))
    S = 0
    M = np.diag(np.arange(N-1, -1, -1), k=0)
    for i in M:
        S += i
    print('Матрица:')
    print(M)
    print('Сумма значений по диагонали:')
    print(S)
    print('Сумма всех значений:')
    print(sum(S))

    
matrix_sum()

Введите число N: 5
Матрица:
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Сумма значений по диагонали:
[4 3 2 1 0]
Сумма всех значений:
10


**Задание 3**

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [52]:
from numpy import linalg

In [54]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [85]:
print(f'{4*0.46666667 + 2*3.84444444 -5.55555555:.2f}')
print(f'{0.46666666 + 3*3.8444444444:.2f}')
print(f'{5*3.84444444 + 4*(-5.55555555):.2f}')

4.00
12.00
-3.00
